In [1]:
import pandas as pd
import numpy as np
import random

randomlist = []
df_demand = {}
random.seed(11) # Use the same random seed
for i in range(0,50):   # 20 depots
    n = random.randint(100,150) # Depot Capacity
    randomlist.append(n)

for i in range(50):
    df_demand[i] = randomlist[i]

sum = 0
for (k,v) in df_demand.items():
    sum = sum + v
    
df_supply = {}
for i in range(sum):
    df_supply[i] = 1.0
    
np.random.seed(11) # Use the same random seed
df_dkm = pd.DataFrame(np.random.uniform(0.5,40, size=(sum,50))).astype(float)

random.seed(11) # Use the same random seed
age_b = []
for i in range(sum):
    n = random.randint(1,3) #Only to generate integer values inclusive of 1 & 3
    age_b.append(n)
    
age = {}
for i in range(len(age_b)):
    age[i] = age_b[i] 
    
kpl = []
co2 = []
random.seed(11) # Use the same random seed
for (k,v) in age.items():
    if (v==1):
        n = random.uniform(5.1,6)
        m = round(random.uniform(515, 524), 2)
        kpl.append(n)
        co2.append(m)
    if (v==2):
        n = random.uniform(4.1,5)
        m = round(random.uniform(525, 534), 2)
        kpl.append(n)
        co2.append(m)
    if (v==3):
        n = random.uniform(3.1,4)
        m = round(random.uniform(535, 540), 2)
        kpl.append(n)
        co2.append(m)
        
fc_kpl = {}
for i in range(sum):
    fc_kpl[i] =(111/ kpl[i])

co2_c = {}
for i in range(sum):
    co2_c[i] =(0.00118642*co2[i])
    
random.seed(11) # Use the same random seed
doc = {}
for i in range(0,50):
    n = random.uniform(50,100)
    doc[i] = n
    
df_tdkom = pd.DataFrame(np.zeros(df_dkm.shape))
for i in range(len(df_dkm.columns)):
    for j in range(len(df_dkm.index)):
        df_tdkom[i][j] = df_dkm[i][j]*fc_kpl[j] + df_dkm[i][j]*co2_c[j] + doc[i]
df_tdkom

/tmp/ipykernel_179386/495549084.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd
/tmp/ipykernel_179386/495549084.py:73: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_tdkom[i][j] = df_dkm[i][j]*fc_kpl[j] + df_dkm[i][j]*co2_c[j] + doc[i]

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,265.089476,110.045903,570.959014,809.125883,507.227612,576.273643,84.611746,574.439733,1033.696049,951.054976,...,141.927512,437.862677,146.936997,384.749900,171.158333,372.223679,893.185248,985.207575,901.272472,665.480383
1,789.512931,504.630819,303.151117,585.172223,925.483587,165.515860,97.309754,968.703026,437.970557,903.636554,...,819.191525,869.657528,298.989276,943.293781,483.711024,583.869094,470.378482,731.793512,863.458148,763.122181
2,399.158571,305.648249,942.645989,384.008117,520.402943,182.087588,368.788542,172.668438,433.227629,802.212062,...,665.994002,993.993839,608.782841,291.073713,804.491856,597.298885,603.717293,216.527381,253.428995,1022.365628
3,1092.241901,1108.002986,486.125158,134.886629,671.751855,867.695487,754.658009,144.633346,339.938476,845.951020,...,258.852521,389.614257,786.657735,328.308832,893.015901,1008.804727,442.860751,397.054192,140.415565,550.559833
4,167.981519,795.073409,951.605591,782.614085,827.970783,826.970803,1176.780995,739.414137,1148.671888,534.845830,...,1225.870405,444.032392,804.197629,786.197683,641.910776,391.163716,511.288451,869.756990,460.135133,530.510379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6283,1297.743983,209.490923,973.150089,708.068628,406.314623,188.700848,755.405703,1230.170126,808.392024,1289.621493,...,756.075941,1330.293311,578.483345,528.235007,616.806401,256.737585,474.247476,1180.838816,769.804582,934.749090
6284,1068.851542,198.328652,480.519122,1203.847007,1184.871348,756.540414,391.200564,862.178477,474.347062,680.030248,...,1227.800164,172.003446,427.826919,654.765713,606.133406,655.536509,1228.743982,960.443100,1234.942625,1011.829600
6285,128.144615,200.501519,855.384725,859.673926,708.448108,961.099764,625.299312,406.411858,535.936765,717.281216,...,189.380527,861.660020,894.150639,978.866631,737.193640,265.586146,903.489722,413.652176,585.822330,488.218803
6286,1156.826269,177.920738,203.004398,394.468131,216.723900,207.686602,490.983774,493.864606,531.326612,465.881696,...,985.789270,744.766356,1110.514375,144.998053,994.662568,304.853086,591.153410,1213.100457,1172.324661,480.258945
6287,456.954110,775.628410,471.449942,414.372014,417.023244,167.676174,192.566279,779.858503,232.162861,806.039830,...,363.488176,963.904233,822.421502,646.960711,235.675849,214.555953,465.928123,531.327935,885.239601,512.655218

In [2]:
df_cost = df_tdkom.copy(deep=True)

In [3]:
df_result = pd.DataFrame(np.zeros(df_tdkom.shape))

while(list(df_supply.values()) and list(df_demand.values())): 
    
    # To find the minimum cost row-wise
    df_nr_list = list(df_tdkom.min(axis=1))
    df_nr = {}
    for i in range(len(df_tdkom.index)):
        df_nr[df_tdkom.index[i]] = df_nr_list[i]
    #df_nr

    # To find the minimum cost column-wise
    df_nc_list = list(df_tdkom.min(axis=0))
    df_nc = {}
    for i in range(len(df_tdkom.columns)):
        df_nc[df_tdkom.columns[i]] = df_nc_list[i]
    #df_nc

    import numpy as np
    stdr = {}
    for i in range(len(df_tdkom.index)):
        stdr[df_tdkom.index[i]] = list(np.std(df_tdkom, axis = 1))[i]
    #stdr

    stdc = {}
    for i in range(len(df_tdkom.columns)):
        stdc[df_tdkom.columns[i]] = list(np.std(df_tdkom, axis = 0))[i]
    #stdc

    r = max(list(stdr.values()) + list(stdc.values()))
    #r

    lst = []
    if(r in stdc.values() and r not in stdr.values()):
        for i in df_tdkom.columns:
            if (stdc[i] == r): 
                for j in (df_tdkom.index):
                    if (df_tdkom.loc[j,i] == df_nc[i]):
                        lst.append([j,i])
                        
        if (len(lst) == 1):
            df_result.loc[lst[0][0],lst[0][1]] = min(df_supply[lst[0][0]],df_demand[lst[0][1]])
            df_supply[lst[0][0]] = df_supply[lst[0][0]] - df_result.loc[lst[0][0],lst[0][1]]
            df_demand[lst[0][1]] = df_demand[lst[0][1]] - df_result.loc[lst[0][0],lst[0][1]]


            if (df_supply[lst[0][0]] == 0 and df_demand[lst[0][1]] == 0):
                df_tdkom = df_tdkom.drop(lst[0][0], axis = 0)
                del df_supply[lst[0][0]]

            elif (df_supply[lst[0][0]] == 0 and df_demand[lst[0][1]] != 0):
                df_tdkom = df_tdkom.drop(lst[0][0], axis = 0)
                del df_supply[lst[0][0]]

            elif (df_supply[lst[0][0]] != 0 and df_demand[lst[0][1]] == 0):
                df_tdkom = df_tdkom.drop(lst[0][1], axis = 1)
                del df_demand[lst[0][1]]
        
        elif (len(lst)!=1):
            minc = df_tdkom.loc[lst[0][0],lst[0][1]]
            for i in range(len(lst)):
                if (minc <= df_tdkom.loc[lst[i][0],lst[i][1]]):
                    minc = minc
                elif (minc > df_tdkom.loc[lst[i][0],lst[i][1]]):
                    minc = df_tdkom.loc[lst[i][0],lst[i][1]]
                    
            lstn = []
            for i in range(len(lst)):
                if (df_tdkom.loc[lst[i][0],lst[i][1]] == minc):
                    lstn.append([lst[i][0],lst[i][1]])

            df_result.loc[lstn[0][0],lstn[0][1]] = min(df_supply[lstn[0][0]],df_demand[lstn[0][1]])
            df_supply[lstn[0][0]] = df_supply[lstn[0][0]] - df_result.loc[lstn[0][0],lstn[0][1]]
            df_demand[lstn[0][1]] = df_demand[lstn[0][1]] - df_result.loc[lstn[0][0],lstn[0][1]]
            
            if (df_supply[lstn[0][0]] == 0 and df_demand[lstn[0][1]] == 0):
                df_tdkom = df_tdkom.drop(lstn[0][0], axis = 0)
                del df_supply[lstn[0][0]]

            elif (df_supply[lstn[0][0]] == 0 and df_demand[lstn[0][1]] != 0):
                df_tdkom = df_tdkom.drop(lstn[0][0], axis = 0)
                del df_supply[lstn[0][0]]

            elif (df_supply[lstn[0][0]] != 0 and df_demand[lstn[0][1]] == 0):
                df_tdkom = df_tdkom.drop(lstn[0][1], axis = 1)
                del df_demand[lstn[0][1]]


    lstm = [] 
    lstr = [] 
    #### Tie in value of SD, selecting minimum TC
    ### Only if same SD appears row-wise and once column-wise
    if(r in stdc.values() and r in stdr.values()):
        min_val = []
        idx_list = []
        for i in df_tdkom.index:
            for j in (df_tdkom.columns):
                if (stdr[i] == r and stdc[j] == r):
                    if (df_nr[i] <= df_nc[j]):
                        for l in df_tdkom.columns:
                            if (df_tdkom.loc[i,l] == df_nr[i]):
                                #print(df_tdkom.loc[i,l], df_nr[i])
                                min_val.append(df_nr[i])
                                idx_list.append([i,l])
                                #lstm.append([i,l])
                    elif (df_nr[i] > df_nc[j]):
                        for o in df_tdkom.index:
                             if (df_tdkom.loc[o,j] == df_nc[j]):
                                    min_val.append(df_nc[j])
                                    idx_list.append([o,j])
                                    #lstm.append([o,j]) 
                    lstm.append(idx_list[min_val.index(min(min_val))])         
 

        ###### Allocating to the left most cell, since that' how it identifies
        df_result.loc[lstm[0][0],lstm[0][1]] = min(df_supply[lstm[0][0]],df_demand[lstm[0][1]])
        df_supply[lstm[0][0]] = df_supply[lstm[0][0]] - df_result.loc[lstm[0][0],lstm[0][1]]
        df_demand[lstm[0][1]] = df_demand[lstm[0][1]] - df_result.loc[lstm[0][0],lstm[0][1]]
        
        
        if (df_supply[lstm[0][0]] == 0 and df_demand[lstm[0][1]] == 0):
            #print(df_supply[lstm[0][0]], df_demand[lstm[0][1]] )
            df_tdkom = df_tdkom.drop(lstm[0][0], axis = 0)
            del df_supply[lstm[0][0]]
            
        elif (df_supply[lstm[0][0]] == 0 and df_demand[lstm[0][1]] != 0):
            #print(df_supply[lstm[0][0]], df_demand[lstm[0][1]] )
            df_tdkom = df_tdkom.drop(lstm[0][0], axis = 0)
            del df_supply[lstm[0][0]]
        
        elif (df_supply[lstm[0][0]] != 0 and df_demand[lstm[0][1]] == 0):
            #print(df_supply[lstm[0][0]], df_demand[lstm[0][1]] )
            df_tdkom = df_tdkom.drop(lstm[0][1], axis = 1)
            del df_demand[lstm[0][1]]

   
    if (r in stdr.values() and r not in stdc.values()):
        for i in df_tdkom.index:
            if (stdr[i] == r): 
                for j in (df_tdkom.columns):
                    if (df_tdkom.loc[i,j] == df_nr[i]):
                        lstr.append([i,j])
        
        if (len(lstr)==1):
            df_result.loc[lstr[0][0],lstr[0][1]] = min(df_supply[lstr[0][0]],df_demand[lstr[0][1]])
            df_supply[lstr[0][0]] = df_supply[lstr[0][0]] - df_result.loc[lstr[0][0],lstr[0][1]]
            df_demand[lstr[0][1]] = df_demand[lstr[0][1]] - df_result.loc[lstr[0][0],lstr[0][1]]  

            if (df_supply[lstr[0][0]] == 0 and df_demand[lstr[0][1]] == 0):
                df_tdkom = df_tdkom.drop(lstr[0][0], axis = 0)
                del df_supply[lstr[0][0]]

            elif (df_supply[lstr[0][0]] == 0 and df_demand[lstr[0][1]] != 0):
                df_tdkom = df_tdkom.drop(lstr[0][0], axis = 0)
                del df_supply[lstr[0][0]]

            elif (df_supply[lstr[0][0]] != 0 and df_demand[lstr[0][1]] == 0):
                df_tdkom = df_tdkom.drop(lstr[0][1], axis = 1)
                del df_demand[lstr[0][1]]
                
        elif (len(lstr)!=1):
            minr = df_tdkom.loc[lstr[0][0],lstr[0][1]]
            for i in range(len(lstr)):
                if (minr <= df_tdkom.loc[lstr[i][0],lstr[i][1]]):
                    minr = minr
                elif (minr > df_tdkom.loc[lstr[i][0],lstr[i][1]]):
                    minr = df_tdkom.loc[lstr[i][0],lstr[i][1]]

            lstp = []
            for i in range(len(lstr)):
                if (df_tdkom.loc[lstr[i][0],lstr[i][1]] == minr):
                    lstp.append([lstr[i][0],lstr[i][1]])

            df_result.loc[lstp[0][0],lstp[0][1]] = min(df_supply[lstp[0][0]],df_demand[lstp[0][1]])
            df_supply[lstp[0][0]] = df_supply[lstp[0][0]] - df_result.loc[lstp[0][0],lstp[0][1]]
            df_demand[lstp[0][1]] = df_demand[lstp[0][1]] - df_result.loc[lstp[0][0],lstp[0][1]]

            if (df_supply[lstp[0][0]] == 0 and df_demand[lstp[0][1]] == 0):
                df_tdkom = df_tdkom.drop(lstp[0][0], axis = 0)
                del df_supply[lstp[0][0]]

            elif (df_supply[lstp[0][0]] == 0 and df_demand[lstp[0][1]] != 0):
                df_tdkom = df_tdkom.drop(lstp[0][0], axis = 0)
                del df_supply[lstp[0][0]]

            elif (df_supply[lstp[0][0]] != 0 and df_demand[lstp[0][1]] == 0):
                df_tdkom = df_tdkom.drop(lstp[0][1], axis = 1)
                del df_demand[lstp[0][1]]

KeyboardInterrupt:

In [ ]:
df_result

In [ ]:
df_final = df_cost.mul(df_result, axis = 0)
df_final.to_numpy().sum()

stop = timeit.default_timer()
execution_time = stop - start

print("Program Executed in "+str(execution_time))